package model;

/**
 * AqUnit generated by MyEclipse Persistence Tools
 */

public class AqUnit implements java.io.Serializable {

	// Fields

	private Integer oid;

	private String name;

	private String id;

	private String id2;

	// Constructors

	/** default constructor */
	public AqUnit() {
	}

	/** full constructor */
	public AqUnit(String name, String id, String id2) {
		this.name = name;
		this.id = id;
		this.id2 = id2;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getId2() {
		return this.id2;
	}

	public void setId2(String id2) {
		this.id2 = id2;
	}

}