package model;

import java.util.Date;

/**
 * Clazz generated by MyEclipse - Hibernate Tools
 */
public class Classes implements java.io.Serializable {
	
	public Integer getOid() {
		return Oid;
	}
	public void setOid(Integer oid) {
		Oid = oid;
	}
	public String getClassNo() {
		return ClassNo;
	}
	public void setClassNo(String classNo) {
		ClassNo = classNo;
	}
	public String getClassName() {
		return ClassName;
	}
	public void setClassName(String className) {
		ClassName = className;
	}
	public String getCampusNo() {
		return CampusNo;
	}
	public void setCampusNo(String campusNo) {
		CampusNo = campusNo;
	}
	public String getSchoolNo() {
		return SchoolNo;
	}
	public void setSchoolNo(String schoolNo) {
		SchoolNo = schoolNo;
	}
	public String getSchoolType() {
		return SchoolType;
	}
	public void setSchoolType(String schoolType) {
		SchoolType = schoolType;
	}
	public String getDeptNo() {
		return DeptNo;
	}
	public void setDeptNo(String deptNo) {
		DeptNo = deptNo;
	}
	public Integer getGrade() {
		return Grade;
	}
	public void setGrade(Integer grade) {
		Grade = grade;
	}
	public String getSeqNo() {
		return SeqNo;
	}
	public void setSeqNo(String seqNo) {
		SeqNo = seqNo;
	}
	public String getType() {
		return Type;
	}
	public void setType(String type) {
		Type = type;
	}
	public String getShortName() {
		return ShortName;
	}
	public void setShortName(String shortName) {
		ShortName = shortName;
	}
	public String getDept() {
		return Dept;
	}
	public void setDept(String dept) {
		Dept = dept;
	}
	public String getEditor() {
		return editor;
	}
	public void setEditor(String editor) {
		this.editor = editor;
	}
	public Date getEditime() {
		return editime;
	}
	public void setEditime(Date editime) {
		this.editime = editime;
	}
	public String getInstNo() {
		return InstNo;
	}
	public void setInstNo(String instNo) {
		InstNo = instNo;
	}
	public String getSchNo() {
		return SchNo;
	}
	public void setSchNo(String schNo) {
		SchNo = schNo;
	}
	public String getTutor() {
		return tutor;
	}
	public void setTutor(String tutor) {
		this.tutor = tutor;
	}
	public String getGraduate() {
		return graduate;
	}
	public void setGraduate(String graduate) {
		this.graduate = graduate;
	}
	
	private Integer Oid;
	private String ClassNo;
	private String ClassName;
	private String CampusNo;
	private String SchoolNo;
	private String SchoolType;
	private String DeptNo;
	private Integer Grade;
	private String SeqNo;
	private String Type;
	private String ShortName;
	private String Dept;
	private String editor;
	private Date editime;
	private String InstNo;
	private String SchNo;
	private String tutor;
	private String graduate;
	
}