package model;

import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Dilg generated by MyEclipse - Hibernate Tools
 */
public class Dilg implements java.io.Serializable {

	private static final long serialVersionUID = 8006336086880578386L;

	private Integer Oid;
	private String student_no;
	private Date date;
	private String cls;
	private String abs;
	private Integer Dtime_oid;
	private Integer Dilg_app_oid;
	private String earlier;
	private String abs_original;

	public Dilg() {

	}

	public Dilg(Integer Oid, String student_no, Date date, String cls,
			String abs, Integer Dtime_oid, Integer Dilg_app_oid,
			String earlier, String abs_original) {
		this.Oid = Oid;
		this.student_no = student_no;
		this.date = date;
		this.cls = cls;
		this.abs = abs;
		this.Dtime_oid = Dtime_oid;
		this.Dilg_app_oid = Dilg_app_oid;
		this.abs_original = abs_original;
		this.earlier = earlier;
	}

	/*
	 * public String getEarlier() { return earlier; }
	 * 
	 * public void setEarlier(String earlier) { this.earlier = earlier; }
	 */

	public String getEarlier() {
		return earlier;
	}

	public void setEarlier(String earlier) {
		this.earlier = earlier;
	}

	public Integer getDilg_app_oid() {
		return Dilg_app_oid;
	}

	public void setDilg_app_oid(Integer dilg_app_oid) {
		Dilg_app_oid = dilg_app_oid;
	}

	public Integer getOid() {
		return Oid;
	}

	public String getAbs_original() {
		return abs_original;
	}

	public void setAbs_original(String abs_original) {
		this.abs_original = abs_original;
	}

	public void setOid(Integer oid) {
		Oid = oid;
	}

	public String getStudent_no() {
		return student_no;
	}

	public void setStudent_no(String student_no) {
		this.student_no = student_no;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getCls() {
		return cls;
	}

	public void setCls(String cls) {
		this.cls = cls;
	}

	public String getAbs() {
		return abs;
	}

	public void setAbs(String abs) {
		this.abs = abs;
	}

	public Integer getDtime_oid() {
		return Dtime_oid;
	}

	public void setDtime_oid(Integer dtime_oid) {
		Dtime_oid = dtime_oid;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}