package model;



/**
 * Just generated by MyEclipse - Hibernate Tools
 */
public class Just {
	
	private String departClass;
	private String studentNo;
	private Integer teacherScore;
	private Integer deptheaderScore;
	private Integer militaryScore;
	private Integer dilgScore;
	private Integer desdScore;
	private Integer meetingScore;
	private Integer totalScore;
	private String comCode1;
	private String comCode2;
	private String comCode3;

	/** default constructor */
	public Just() {
	}

	public String getDepartClass() {
		return departClass;
	}

	public void setDepartClass(String departClass) {
		this.departClass = departClass;
	}

	public String getStudentNo() {
		return studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public Integer getTeacherScore() {
		return teacherScore;
	}

	public void setTeacherScore(Integer teacherScore) {
		this.teacherScore = teacherScore;
	}

	public Integer getDeptheaderScore() {
		return deptheaderScore;
	}

	public void setDeptheaderScore(Integer deptheaderScore) {
		this.deptheaderScore = deptheaderScore;
	}

	public Integer getMilitaryScore() {
		return militaryScore;
	}

	public void setMilitaryScore(Integer militaryScore) {
		this.militaryScore = militaryScore;
	}

	public Integer getDilgScore() {
		return dilgScore;
	}

	public void setDilgScore(Integer dilgScore) {
		this.dilgScore = dilgScore;
	}

	public Integer getDesdScore() {
		return desdScore;
	}

	public void setDesdScore(Integer desdScore) {
		this.desdScore = desdScore;
	}

	public Integer getMeetingScore() {
		return meetingScore;
	}

	public void setMeetingScore(Integer meetingScore) {
		this.meetingScore = meetingScore;
	}

	public Integer getTotalScore() {
		return totalScore;
	}

	public void setTotalScore(Integer totalScore) {
		this.totalScore = totalScore;
	}

	public String getComCode1() {
		return comCode1;
	}

	public void setComCode1(String comCode1) {
		this.comCode1 = comCode1;
	}

	public String getComCode2() {
		return comCode2;
	}

	public void setComCode2(String comCode2) {
		this.comCode2 = comCode2;
	}

	public String getComCode3() {
		return comCode3;
	}

	public void setComCode3(String comCode3) {
		this.comCode3 = comCode3;
	}

	

}