package model;

import java.util.Date;

/**
 * PubCalendar generated by MyEclipse Persistence Tools
 */

public class PubCalendar implements java.io.Serializable {

	// Fields

	private Integer oid;

	private String account;

	private String name;

	private String place;

	private Date begin;

	private Date end;

	private String members;

	private String note;

	private String type;

	private String color;

	private String no;

	private String sender;
	
	private String rec_type;
	
	private Integer rec_event_length;	

	/** default constructor */
	public PubCalendar() {
	}

	/** full constructor */
	public PubCalendar(String account, String name, String place, Date begin,
			Date end, String members, String note, String type,
			String color, String no, String sender, String rec_type, Integer rec_event_length) {
		this.account = account;
		this.name = name;
		this.place = place;
		this.begin = begin;
		this.end = end;
		this.members = members;
		this.note = note;
		this.type = type;
		this.color = color;
		this.no = no;
		this.sender = sender;
		this.rec_type=rec_type;
		this.rec_event_length=rec_event_length;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public String getMembers() {
		return this.members;
	}

	public void setMembers(String members) {
		this.members = members;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}
	
	public Integer getRec_event_length() {
		return rec_event_length;
	}
	
	public void setRec_event_length(Integer rec_event_length) {
		this.rec_event_length = rec_event_length;
	}
	
	public void setRec_type(String rec_type) {
		this.rec_type = rec_type;
	}
	
	public String getRec_type() {
		return rec_type;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}
	
	public Date getBegin() {
		return this.begin;
	}

}